### ISSUE TITLE
Some cursors are not closed

### ISSUE THREAD

**Issue by costular** [naman14/TimberX#1]
I saw some methods where you aren't closing cursors which is very important for memory handling.

https://github.com/naman14/TimberX/blob/df1a7cf82adf0d8193fe2e70b7bd6a4276faf69f/app/src/main/java/com/naman14/timberx/util/MusicUtils.kt#L174

**Comment by afollestad** [comment]
https://github.com/naman14/TimberX/pull/3 will help

**Comment by naman14** [comment]
Yeah, should be fixed with #3. Please reopen if there any other places where cursor is not closed
