### ISSUE TITLE
Spotify integration

### ISSUE THREAD

**Issue by danieldaeschle** [naman14/TimberX#10]
Is it possible to add a fully spotify integration? It would be very nice as an alternative client if it is better.

**Comment by naman14** [comment]
Spotify integration will not be possible and is not planned

**Comment by lohriialo** [comment]
Would be awesome to have some sort of Spotify integration.

There's an app called SpotyTube that let's you play music videos from Spotify playlist https://play.google.com/store/apps/details?id=me.spotytube.spotytube
