### ISSUE TITLE
Touch target size is too small for "Playlist" and "Back" buttons in Now playing view

### ISSUE THREAD

**Issue by hellpe** [naman14/TimberX#100]
**App Version:**

v1.5
 
**Affected Device(s):**

Xiaomi Mi A2 Lite with Android 9
 
**Describe the Bug:**

The "Back (top left) and "Playlist" (bottom right) buttons in the individual song view have a very small touch target size, forcing the user to touch precisely the button icon in order to activate it

**To Reproduce:**
1. Start playing any song
2. Open the Now Playing view
3. Tap close to the "Playlist" or "Back" buttons

**Expected Behavior:**

Clicking in a blank area surrounding the buttons should trigger them anyway

**Comment by naman14** [comment]
Have increased the target areas for these buttons
