### ISSUE TITLE
Dark/amoled themes

### ISSUE THREAD

**Issue by KeziahMoselle** [naman14/TimberX#16]
I would like to see a dark mode (dark grey / OLED theme) on this app.
It would make this application perfect !

**Comment by naman14** [comment]
@afollestad
In Timber I used app-theme-engine but that still resulted in too much theming specific code but this project doesn't have that many UI elements.
I think we can use https://github.com/afollestad/aesthetic for adding theming support?

**Comment by afollestad** [comment]
@naman14 we definitely can - although it wouldn't be too difficult to provide a light/dark/amoled theme just with styles.xml if we can do without color customization

**Comment by naman14** [comment]
Yeah, Wouldn't be providing color customisation for now, will go ahead with styles for now

**Comment by afollestad** [comment]
Sweet - you can just use custom attributes to switch out colors and such everywhere - and you can use those attributes right in your drawables so there's no need to have multiple icon files defined for different themes @naman14

**Comment by naman14** [comment]
Released in https://github.com/naman14/TimberX/releases/tag/V1.5

**Comment by KeziahMoselle** [comment]
That was fast ! Thank's :smile:
