### ISSUE TITLE
List of enhancements

### ISSUE THREAD

**Issue by Anutha02** [naman14/TimberX#25]
I want to suggest a few enhancements that would make the app even better and also report some bugs:
1. On clicking the search icon there is an abrupt switch to the search ui, a Transition would be better.
2. Change the font to Google Product sans.
3. Increase the size of the shuffle and repeat icons.
4. The create playlists extended fab moves scrolls up with the scrolling of the album's list.
5. Use Adaptive icon.
6. If you are using the new outlined icons, then the pause icon should also be outlined to match other icons.
7. Increase the height(width) of the song progress indicator in the minimised form as it is barely visible in smaller screens.

**Comment by costular** [comment]
Google Product Sans can't be used according to [its license](https://fonts.google.com/license/productsans).

**Comment by Anutha02** [comment]
Well then we could use some alternative, like futura

**Comment by afollestad** [comment]
Why are you thumbs up-ing all of your issues? Lol.

These should all go in separate issues though - an issue is supposed to be focused on one thing.

**Comment by Anutha02** [comment]
Okay... I will open separate issues then...
