### ISSUE TITLE
Option menu not working

### ISSUE THREAD

**Issue by lohriialo** [naman14/TimberX#27]
App version:  1.2

Option menu clicked isn't working in the "Now Playing" view/activity (menu at the top right corner)

**Comment by afollestad** [comment]
Will take a look at this later

**Comment by afollestad** [comment]
Unable to reproduce any issues here - there is no overflow menu in the now playing screen?

**Comment by lohriialo** [comment]
Option menu on toolbar no longer available, hence not reproducible anymore after pulling latest commits

**Comment by afollestad** [comment]
Ah, got it
