### ISSUE TITLE
Notification sticks indefinitly

### ISSUE THREAD

**Issue by ArunKumar28** [naman14/TimberX#32]
Add removable notification on stopped music file

**Comment by afollestad** [comment]
I believe this is a duplicate of https://github.com/naman14/TimberX/issues/30.

**Comment by ArunKumar28** [comment]
But i have updated playstore app installed,there is no cross button

**Comment by afollestad** [comment]
This has not been implemented yet. The linked issue is still open.

**Comment by ArunKumar28** [comment]
Ok

**Comment by naman14** [comment]
Will do this in next release
