### ISSUE TITLE
New logo so the app stand out in play store

### ISSUE THREAD

**Issue by hutriteguh** [naman14/TimberX#36]
Great app, I am curently using this app as my music player. I really love it simple UI. 
I think you need to revamp the logo so your app will stand out in the sea of music player in play store. I can design a new logo for you, I am a graphic designer and love to contribute to open source project as a practice to get better in graphic design. just let me know if you want a new logo for TimberX. cheers.

**Comment by afollestad** [comment]
Also see https://github.com/naman14/TimberX/issues/31

**Comment by afollestad** [comment]
Closing in favor of https://github.com/naman14/TimberX/issues/31, please comment on that instead
