### ISSUE TITLE
Add CI to test PRs and branches for successful builds 

### ISSUE THREAD

**Issue by afollestad** [naman14/TimberX#4]
All that you gotta do is create an account on [Travis.ci](https://travis-ci.org) and add the repository. I can add the configuration to the repo here when you're ready, and we can add a badge to the README.

IMO this is very important because we want to make sure master is building successfully and that PRs won't break anything if they are merged (especially if unit tests are added to the repo). 😁

**Comment by afollestad** [comment]
All that you gotta do is create an account on [Travis.ci](https://travis-ci.org) and add the repository. I can add the configuration to the repo here when you're ready, and we can add a badge to the README.

IMO this is very important because we want to make sure master is building successfully and that PRs won't break anything if they are merged (especially if unit tests are added to the repo). 😁

**Comment by naman14** [comment]
Added the travis config and build status in readme

**Comment by afollestad** [comment]
Awesome!
