### ISSUE TITLE
How to add music and albums?

### ISSUE THREAD

**Issue by Vegas10128** [naman14/TimberX#45]
Cannot find any instructions or an area within the app on android studio about how to link any music to the app. Is there a folder for the music? 
is there any server scripts i need to get?

**Comment by paolovalerdi** [comment]
Just add your files in your Music folder in internal storage. Timber works with local files.

**Comment by Vegas10128** [comment]
Thanks for the reply! But i dont really need this app then. 
I have been trying to look for something along the lines of this 
https://codecanyon.net/item/cherry-android-online-music-player/22305318?s_rank=14

it does not need to have an php server. But i need an music app that has the music installed within the app and does not provide local library songs.

**Comment by afollestad** [comment]
This app uses Android's media store (system wide database) to find your music, local music only.
