### ISSUE TITLE
Place title on queue screen

### ISSUE THREAD

**Issue by deandreamatias** [naman14/TimberX#77]
*Please consider making a Pull Request if you are capable of doing so.*

**Description what you'd like to happen:**

The queue screen has no title. The user at this time does not know where he is.
![Screenshot_20190330-232349](https://user-images.githubusercontent.com/21011641/55282465-840f7d80-5344-11e9-98a0-8fb705db3421.jpg)

**Describe alternatives you've considered:**

Place a title like:

- Play queue (used in Spotify)
- Queue

Step to reproduce:

1. Play a playlist, album or other with 2 or more songs.
2. Click on the following music (below - Up Next)
3. See the screen without a title.

PS: If this issue is accepted, I could do it myself.

**Comment by naman14** [comment]
Fixed
