### ISSUE TITLE
Blank screen when first launching the app

### ISSUE THREAD

**Issue by linux43** [naman14/TimberX#94]
Hello
I tested TimberX from your publish on Google Play and also by self produced git, on both I noticed a blank white screen when launching the app for the first time. In order to get passed that I had to close the app and reopen it.
This issue is very critic because when people download and app and it won't run on the first launch, they won't try again, they'll just delete it

Version: latest
Device: Galaxy S8, Android Studio Emulator (Pixel 3)

**Comment by naman14** [comment]
Have fixed this
